name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/inventory-management-api
            git pull origin master
             # Install yarn if not available
            if ! command -v yarn &> /dev/null
            then
              echo "Yarn not found. Installing yarn..."
              npm install -g yarn
            fi

            # Install pm2 if not available
            if ! command -v pm2 &> /dev/null
            then
              echo "PM2 not found. Installing pm2..."
              npm install -g pm2
            fi
            yarn install --frozen-lockfile
            npx prisma migrate deploy
            yarn build
            pm2 restart all  # Or the command to restart your application

